// <auto-generated />
using System;
using DazzleJewelry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DazzleJewelry.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210502124825_AddingIdentity")]
    partial class AddingIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DazzleJewelry.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescripton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Küpe"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Yüzük"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Kolye"
                        });
                });

            modelBuilder.Entity("DazzleJewelry.Models.Jewelry", b =>
                {
                    b.Property<int>("JewelryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgThumUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("JewelryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Jewelries");

                    b.HasData(
                        new
                        {
                            JewelryId = 1,
                            CategoryId = 1,
                            Description = "Vintage Küpelerimiz, altın suyuna batırılmış pirinçten yapılmaktadır. Uzun süreli kullanımlara uygundur. Kararma ve solma yapmaz. Hassas, alerjik yapılı ciltler için önerilmez.Kullanım Şartları-Parfüm,krem ve bol suya temasından kaçınınız.- Kullanılmadığı zamanlarda,küpenizi ışıktan uzak ve hava almayan bir kutuda muhafaza ediniz.",
                            ImgThumUrl = "\\images\\thumbnails\\minimal-simsek-kupe---k113-b029 (1).jpg",
                            ImgUrl = "\\images\\minimal-simsek-kupe---k113-b029.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Minimal Şimşek Küpe",
                            Price = 34.0m
                        },
                        new
                        {
                            JewelryId = 2,
                            CategoryId = 2,
                            Description = "Yüzüklerimiz ayarlanabilir olmanın yanı sıra pirinç üzeri altın kaplama olup, kimyasal maddeler ile temasından kaçınmanız halinde uzun süreli kullanıma uygundur.Ayarlanabilir tasarım yüzüklerimiz,çeşitli figür ve renk detaylarıyla kombinlerinizde dikkat çeken ayrıntılar olarak yer alacaktır.Son moda gold veya gümüş renkli yüzüklerimizi her parmağa uygun ayarlanabilir yapısı ile tüm parmaklarda kullanılabilir.Dilerseniz eklem yüzüğü,dilerseniz normal yüzük olarak da kullanabileceğiniz altın kaplama yüzüklerimizi kolye,bileklik gibi diğer takı çeşitlerinin yanı sıra son moda kıyafetlerinizle,gözlük ve saat benzeri aksesuarlarınız ile kombinleyip ellerinizin güzelliğini ön plana çıkarabilirsiniz.",
                            ImgThumUrl = "\\images\\thumbnails\\ayarlanabilir-flat-earth-yuzuk---y20-a285 (1).jpg",
                            ImgUrl = "\\images\\ayarlanabilir-flat-earth-yuzuk---y20-a285.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Ayarlanabilir Flat Earth Yüzük",
                            Price = 39.0m
                        },
                        new
                        {
                            JewelryId = 3,
                            CategoryId = 3,
                            Description = "Tasarım Kolye Modellerimiz günlük hayatta veya iş, düğün gibi özel günlerinizde kıyafetlerinizin parlayan parçaları olacaklar. Altın suyuna batırılmış pirinçten üretilen tasarım kolyeleri istediğiniz zincir uzunluğunu seçerek sipariş verebilirsiniz. Farklı uzunluklar seçerek kolye kombinlerinizi kendiniz oluşturabilirsiniz. Zirkon Taşlı, hayvan, kalp, nesne figürlü tasarım kolye modellerimizi sizler için özenle şeffaf ambalajda hazırlayıp özel Dazzlecave mühürlü kutularda gönderiyoruz. Hediye kolye olarak çok sevilen mühürlü kutularımızın içine istediğiniz hediye notunu sipariş aşamasında yazabilirsiniz. Kullanım TavsiyeleriAltın kaplama tasarım kolyelerinizi uzun süreli kullanımını sağlamak için;Parfüm, krem gibi kimyasal maddeler ile temas etmemesine dikkat edilmelidir. Deniz, duş veya havuza girilmesi tavsiye edilmemektedir.Takılarınızı birbirine temas etmeyecek şekilde kapalı bir kutu veya kesede muhafaza etmenizi tavsiye ederiz.Hassas cilter için önerilmemektedir.",
                            ImgThumUrl = "\\images\\thumbnails\\hilal-kolye---vk289-34d7 (1).jpg",
                            ImgUrl = "\\images\\hilal-kolye---vk289-34d7.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Hilal Kolye",
                            Price = 49.0m
                        },
                        new
                        {
                            JewelryId = 4,
                            CategoryId = 2,
                            Description = "Yüzüklerimiz ayarlanabilir olmanın yanı sıra pirinç üzeri altın kaplama olup, kimyasal maddeler ile temasından kaçınmanız halinde uzun süreli kullanıma uygundur.Ayarlanabilir tasarım yüzüklerimiz,çeşitli figür ve renk detaylarıyla kombinlerinizde dikkat çeken ayrıntılar olarak yer alacaktır.Son moda gold veya gümüş renkli yüzüklerimizi her parmağa uygun ayarlanabilir yapısı ile tüm parmaklarda kullanılabilir.Dilerseniz eklem yüzüğü,dilerseniz normal yüzük olarak da kullanabileceğiniz altın kaplama yüzüklerimizi kolye, bileklik gibi diğer takı çeşitlerinin yanı sıra son moda kıyafetlerinizle,gözlük ve saat benzeri aksesuarlarınız ile kombinleyip ellerinizin güzelliğini ön plana çıkarabilirsiniz.",
                            ImgThumUrl = "\\images\\thumbnails\\gumus-renk-ayarlanabilir-zincir-yuzuk--d34-41 (1).jpg",
                            ImgUrl = "\\images\\gumus-renk-ayarlanabilir-zincir-yuzuk--d34-41.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Gümüş Renk Ayarlanabilir Zincir Yüzük",
                            Price = 34.0m
                        },
                        new
                        {
                            JewelryId = 5,
                            CategoryId = 2,
                            Description = "Yüzüklerimiz ayarlanabilir olmanın yanı sıra pirinç üzeri altın kaplama olup, kimyasal maddeler ile temasından kaçınmanız halinde uzun süreli kullanıma uygundur.Ayarlanabilir tasarım yüzüklerimiz,çeşitli figür ve renk detaylarıyla kombinlerinizde dikkat çeken ayrıntılar olarak yer alacaktır.Son moda gold veya gümüş renkli yüzüklerimizi her parmağa uygun ayarlanabilir yapısı ile tüm parmaklarda kullanılabilir.Dilerseniz eklem yüzüğü,dilerseniz normal yüzük olarak da kullanabileceğiniz altın kaplama yüzüklerimizi kolye, bileklik gibi diğer takı çeşitlerinin yanı sıra son moda kıyafetlerinizle,gözlük ve saat benzeri aksesuarlarınız ile kombinleyip ellerinizin güzelliğini ön plana çıkarabilirsiniz.",
                            ImgThumUrl = "\\images\\thumbnails\\ayarlanabilir-elips-madalyon-yuzuk---y22-0309 (1).jpg",
                            ImgUrl = "\\images\\ayarlanabilir-elips-madalyon-yuzuk---y22-0309.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Ayarlanabilir Elips Madalyon Yüzük",
                            Price = 39.0m
                        },
                        new
                        {
                            JewelryId = 6,
                            CategoryId = 1,
                            Description = "Kullanım TavsiyeleriAltın kaplama tasarım kolyelerinizi uzun süreli kullanımını sağlamak için;Parfüm, krem gibi kimyasal maddeler ile temas etmemesine dikkat edilmelidir.Deniz, duş veya havuza girilmesi tavsiye edilmemektedir.Takılarınızı birbirine temas etmeyecek şekilde kapalı bir kutu veya kesede muhafaza etmenizi tavsiye ederiz.Hassas cilter için önerilmemektedir.",
                            ImgThumUrl = "\\images\\thumbnails\\buyuk-halka-kupe---k155-1-1838 (1).jpg",
                            ImgUrl = "\\images\\buyuk-halka-kupe---k155-1-1838.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Büyük Halka Küpe",
                            Price = 39.0m
                        },
                        new
                        {
                            JewelryId = 7,
                            CategoryId = 3,
                            Description = "Tasarım Kolye Modellerimiz günlük hayatta veya iş, düğün gibi özel günlerinizde kıyafetlerinizin parlayan parçaları olacaklar. Altın suyuna batırılmış pirinçten üretilen tasarım kolyeleri istediğiniz zincir uzunluğunu seçerek sipariş verebilirsiniz. Farklı uzunluklar seçerek kolye kombinlerinizi kendiniz oluşturabilirsiniz. Zirkon Taşlı, hayvan, kalp, nesne figürlü tasarım kolye modellerimizi sizler için özenle şeffaf ambalajda hazırlayıp özel Dazzlecave mühürlü kutularda gönderiyoruz. Hediye kolye olarak çok sevilen mühürlü kutularımızın içine istediğiniz hediye notunu sipariş aşamasında yazabilirsiniz. ",
                            ImgThumUrl = "\\images\\thumbnails\\tasli-yonca-kolye---vk298-f27b (1).jpg",
                            ImgUrl = "\\images\\tasli-yonca-kolye---vk298-f27b.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Taşlı Yonca Kolye",
                            Price = 44.0m
                        });
                });

            modelBuilder.Entity("DazzleJewelry.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DazzleJewelry.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("JewelryId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("JewelryId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DazzleJewelry.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("JewelryId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("JewelryId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DazzleJewelry.Models.Jewelry", b =>
                {
                    b.HasOne("DazzleJewelry.Models.Category", "Category")
                        .WithMany("Jewelries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DazzleJewelry.Models.OrderDetail", b =>
                {
                    b.HasOne("DazzleJewelry.Models.Jewelry", "Jewelry")
                        .WithMany()
                        .HasForeignKey("JewelryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DazzleJewelry.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jewelry");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DazzleJewelry.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("DazzleJewelry.Models.Jewelry", "Jewelry")
                        .WithMany()
                        .HasForeignKey("JewelryId");

                    b.Navigation("Jewelry");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DazzleJewelry.Models.Category", b =>
                {
                    b.Navigation("Jewelries");
                });

            modelBuilder.Entity("DazzleJewelry.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
